version: '3'
services:
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./log/:/var/log/mysql/
    #   - mysql-data:/var/lib/mysql
    #   - ./scripts:/docker-entrypoint-initdb.d
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: g(cnNTkoQWH{ckM3nWr/79JphJLxjY 
      MYSQL_USER: dena
      MYSQL_PASSWORD: g(cnNTkoQWH{ckM3nWr/79JphJLxjY 
      MYSQL_DATABASE: mysqldb

# volumes:
#   mysql-data:
#     external:
#       name: mysql57_volume
