version: '3'
services:
  mysql:
    image: mysql
    ports:
          - 3306:3306
    # volumes:
    #   - mysql-data:/var/lib/mysql
    #   - ./scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ""
      # MYSQL_USER: dena
      # MYSQL_PASSWORD: dena
      MYSQL_DATABASE: mysql

# volumes:
#   mysql-data:
#     external:
#       name: mysql57_volume
